# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yardsaleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonToSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yardsaleapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='ReasonToSell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yardsaleapp.ReasonToSell'),
        ),
    ]
